import { ReactQueryProvider } from "./ReactQueryProvider";
import "./globals.css";

export const metadata = {
  title: "Foodie",
  description: "Generated by Foodie",
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <main className="flex min-h-screen flex-col items-center container mx-auto px-2 md:px-0 py-12">
            {children}
          </main>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
