const datas = {
  results: [
    {
      type: "item",
      item: {
        nutrition_visibility: "auto",
        country: "US",
        instructions: [
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 75011,
            position: 1,
            display_text:
              "Make the potato mochi: Prepare the mashed potatoes according to the package instructions. Let cool at room temperature for 15 minutes.",
          },
          {
            start_time: 15666,
            appliance: null,
            end_time: 17833,
            temperature: null,
            id: 75012,
            position: 2,
            display_text:
              "In a medium bowl, combine the mashed potatoes and potato starch, using a rubber spatula to mix until the starch is completely absorbed and no longer visible. Let sit for 15 minutes for the potatoes to absorb the starch.",
          },
          {
            start_time: 18000,
            appliance: null,
            end_time: 21000,
            temperature: null,
            id: 75013,
            position: 3,
            display_text:
              "Use a scoop to portion the potato mixture into 8 2-ounce balls.",
          },
          {
            start_time: 22000,
            appliance: null,
            end_time: 25833,
            temperature: null,
            id: 75014,
            position: 4,
            display_text:
              "Flatten a ball with your palms, then place a cube of cheese in the center. Wrap the dough around the cheese to seal completely, then pinch together the seams and shape into a patty. Repeat with the remaining potato mixture and cheese.",
          },
          {
            start_time: 31500,
            appliance: null,
            end_time: 37000,
            temperature: null,
            id: 75015,
            position: 5,
            display_text:
              "Make the yaki sauce: In a small pan, combine the soy sauce, mirin, brown sugar, sake, and garlic. Bring to a simmer over medium heat and cook until the sauce has thickened and looks glossy, about 5 minutes. Remove the pan from the heat.",
          },
          {
            start_time: 38000,
            appliance: null,
            end_time: 40166,
            temperature: null,
            id: 75016,
            position: 6,
            display_text:
              "Add enough canola oil to a large skillet to coat the bottom. Heat over medium heat, then add the potato patties and cook for 3–4 minutes per side, until golden brown.",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 75017,
            position: 7,
            display_text:
              "Turn off the heat and pour the yaki sauce into the pan. Let the residual heat thicken the sauce, flipping the potato patties until evenly glazed.",
          },
          {
            start_time: 42000,
            appliance: null,
            end_time: 42666,
            temperature: null,
            id: 75018,
            position: 8,
            display_text:
              "Wrap a strip of nori around each potato mochi, then serve immediately.",
          },
          {
            start_time: 43000,
            appliance: null,
            end_time: 45000,
            temperature: null,
            id: 75019,
            position: 9,
            display_text: "Enjoy!",
          },
        ],
        keywords: ", cheese, japanese, mochi, potato",
        facebook_posts: [],
        language: "eng",
        seo_path: null,
        user_ratings: {
          count_positive: 9,
          score: 0.6428571428571429,
          count_negative: 5,
        },
        price: {
          total: 300,
          updated_at: "2023-07-06T07:30:08+02:00",
          portion: 100,
          consumption_total: 100,
          consumption_portion: 50,
        },
        id: 8681,
        brand: null,
        slug: "potato-cheese-mochi",
        servings_noun_singular: "serving",
        show_id: 17,
        prep_time_minutes: null,
        sections: [
          {
            components: [
              {
                raw_text:
                  "1 4-ounce package Idahoan® Buttery Homestyle Mashed Potatoes",
                extra_comment: "",
                ingredient: {
                  updated_at: 1688047385,
                  name: "Idahoan® Buttery Homestyle Mashed Potatoes",
                  created_at: 1688047385,
                  display_plural: "Idahoan® Buttery Homestyle Mashed Potatoes",
                  id: 11368,
                  display_singular: "Idahoan® Buttery Homestyle Mashed Potato",
                },
                id: 99735,
                position: 2,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "package",
                      display_plural: "packages",
                      display_singular: "package",
                      abbreviation: "package",
                    },
                    quantity: "1",
                    id: 737565,
                  },
                  {
                    unit: {
                      system: "imperial",
                      name: "ounce",
                      display_plural: "oz",
                      display_singular: "oz",
                      abbreviation: "oz",
                    },
                    quantity: "4",
                    id: 737562,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "105",
                    id: 737560,
                  },
                ],
              },
              {
                raw_text: "150 grams potato starch",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035135,
                  name: "potato starch",
                  created_at: 1500244121,
                  display_plural: "potato starches",
                  id: 2225,
                  display_singular: "potato starch",
                },
                id: 99736,
                position: 3,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "1 ¼",
                    id: 737572,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "150",
                    id: 737571,
                  },
                ],
              },
              {
                raw_text:
                  "4 ounces low-moisture mozzarella cheese, cut into 1-inch cubes",
                extra_comment: "cut into 1-inch (2.54-cm) cubes",
                ingredient: {
                  updated_at: 1685656955,
                  name: "low-moisture mozzarella cheese",
                  created_at: 1685656955,
                  display_plural: "low-moisture mozzarella cheeses",
                  id: 11234,
                  display_singular: "low-moisture mozzarella cheese",
                },
                id: 99737,
                position: 4,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "ounce",
                      display_plural: "oz",
                      display_singular: "oz",
                      abbreviation: "oz",
                    },
                    quantity: "4",
                    id: 737566,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "105",
                    id: 737563,
                  },
                ],
              },
              {
                raw_text: "2 tablespoons canola oil",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035230,
                  name: "canola oil",
                  created_at: 1495764700,
                  display_plural: "canola oils",
                  id: 825,
                  display_singular: "canola oil",
                },
                id: 99738,
                position: 5,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "2",
                    id: 737559,
                  },
                ],
              },
            ],
            name: "Potato Mochi",
            position: 1,
          },
          {
            components: [
              {
                raw_text: "½ cup soy sauce",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035287,
                  name: "soy sauce",
                  created_at: 1493314932,
                  display_plural: "soy sauces",
                  id: 28,
                  display_singular: "soy sauce",
                },
                id: 99740,
                position: 7,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "½",
                    id: 737561,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "milliliter",
                      display_plural: "mL",
                      display_singular: "mL",
                      abbreviation: "mL",
                    },
                    quantity: "120",
                    id: 737558,
                  },
                ],
              },
              {
                raw_text: "½ cup mirin",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035273,
                  name: "mirin",
                  created_at: 1494805898,
                  display_plural: "mirins",
                  id: 287,
                  display_singular: "mirin",
                },
                id: 99741,
                position: 8,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "½",
                    id: 737567,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "milliliter",
                      display_plural: "mL",
                      display_singular: "mL",
                      abbreviation: "mL",
                    },
                    quantity: "120",
                    id: 737564,
                  },
                ],
              },
              {
                raw_text: "1 tablespoon brown sugar",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035289,
                  name: "brown sugar",
                  created_at: 1493307081,
                  display_plural: "brown sugars",
                  id: 6,
                  display_singular: "brown sugar",
                },
                id: 99742,
                position: 9,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "1",
                    id: 737557,
                  },
                ],
              },
              {
                raw_text: "2 tablespoons sake",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035273,
                  name: "sake",
                  created_at: 1494805882,
                  display_plural: "sakes",
                  id: 286,
                  display_singular: "sake",
                },
                id: 99743,
                position: 10,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "2",
                    id: 737569,
                  },
                ],
              },
              {
                raw_text: "2 garlic cloves, smashed",
                extra_comment: "smashed",
                ingredient: {
                  updated_at: 1509035270,
                  name: "garlic cloves",
                  created_at: 1494874431,
                  display_plural: "garlic cloves",
                  id: 321,
                  display_singular: "garlic clove",
                },
                id: 99744,
                position: 11,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "2",
                    id: 737570,
                  },
                ],
              },
              {
                raw_text: "1 sheet sushi nori, cut into 1-inch strips",
                extra_comment: "cut into 1-inch (2.54-cm) strips",
                ingredient: {
                  updated_at: 1688047609,
                  name: "sushi nori",
                  created_at: 1688047609,
                  display_plural: "sushi noris",
                  id: 11370,
                  display_singular: "sushi nori",
                },
                id: 99745,
                position: 12,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "sheet",
                      display_plural: "sheets",
                      display_singular: "sheet",
                      abbreviation: "sheet",
                    },
                    quantity: "1",
                    id: 737568,
                  },
                ],
              },
            ],
            name: "Yaki Glaze",
            position: 2,
          },
        ],
        brand_id: null,
        tags: [
          {
            root_tag_type: "cooking_style",
            name: "comfort_food",
            id: 64462,
            display_name: "Comfort Food",
            type: "cooking_style",
          },
          {
            root_tag_type: "difficulty",
            name: "easy",
            id: 64471,
            display_name: "Easy",
            type: "difficulty",
          },
          {
            root_tag_type: "appliance",
            name: "stove_top",
            id: 65848,
            display_name: "Stove Top",
            type: "appliance",
          },
          {
            root_tag_type: "cooking_style",
            name: "pan_fry",
            id: 65859,
            display_name: "Pan Fry",
            type: "cooking_style",
          },
          {
            root_tag_type: "equipment",
            name: "saute_pan",
            id: 1247787,
            display_name: "Saute Pan",
            type: "equipment",
          },
          {
            root_tag_type: "equipment",
            name: "mixing_bowl",
            id: 1280510,
            display_name: "Mixing Bowl",
            type: "equipment",
          },
          {
            root_tag_type: "difficulty",
            name: "under_1_hour",
            id: 8091748,
            display_name: "Under 1 Hour",
            type: "difficulty",
          },
          {
            root_tag_type: "cuisine",
            name: "asian",
            id: 9295873,
            display_name: "Asian",
            type: "cuisine",
          },
        ],
        nutrition: {},
        name: "Potato Cheese Mochi",
        compilations: [],
        num_servings: 4,
        buzz_id: null,
        tips_and_ratings_enabled: true,
        aspect_ratio: "9:16",
        show: {
          name: "Tasty",
          id: 17,
        },
        created_at: 1687984524,
        description: "Potato mochi is so cute and easy to make!",
        draft_status: "published",
        inspired_by_url: null,
        thumbnail_url:
          "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/452373.jpg",
        thumbnail_alt_text: "",
        total_time_minutes: null,
        video_url: "https://vid.tasty.co/output/294922/hls24_1687278652.m3u8",
        updated_at: 1688053519,
        credits: [
          {
            name: "Brent Bennett",
            type: "internal",
          },
        ],
        approved_at: 1688053519,
        is_one_top: false,
        servings_noun_plural: "servings",
        renditions: [
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/294922/square_720/1687278652_00001.png",
            file_size: 8578774,
            url: "https://vid.tasty.co/output/294922/square_720/1687278652",
            duration: 47798,
            bit_rate: 1436,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 404,
            minimum_bit_rate: null,
            name: "mp4_404x720",
            maximum_bit_rate: null,
            height: 720,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/294922/square_320/1687278652_00001.png",
            file_size: 3113878,
            url: "https://vid.tasty.co/output/294922/square_320/1687278652",
            duration: 47798,
            bit_rate: 522,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 180,
            minimum_bit_rate: null,
            name: "mp4_180x320",
            maximum_bit_rate: null,
            height: 320,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/294922/landscape_720/1687278652_00001.png",
            file_size: 8576823,
            url: "https://vid.tasty.co/output/294922/landscape_720/1687278652",
            duration: 47798,
            bit_rate: 1436,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 404,
            minimum_bit_rate: null,
            name: "mp4_404x720",
            maximum_bit_rate: null,
            height: 720,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/294922/landscape_480/1687278652_00001.png",
            file_size: 4952217,
            url: "https://vid.tasty.co/output/294922/landscape_480/1687278652",
            duration: 47798,
            bit_rate: 829,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 270,
            minimum_bit_rate: null,
            name: "mp4_270x480",
            maximum_bit_rate: null,
            height: 480,
          },
          {
            container: "ts",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/294922/1445289064805-h2exzu/1687278652_00001.png",
            file_size: null,
            url: "https://vid.tasty.co/output/294922/hls24_1687278652.m3u8",
            duration: 47840,
            bit_rate: null,
            content_type: "application/vnd.apple.mpegurl",
            aspect: "portrait",
            width: 608,
            minimum_bit_rate: 276,
            name: "low",
            maximum_bit_rate: 2261,
            height: 1080,
          },
        ],
        beauty_url: null,
        is_shoppable: true,
        topics: [
          {
            name: "Romantic Dinners",
            slug: "romantic-dinners",
          },
        ],
        total_time_tier: null,
        video_ad_content: "editorial_sponsorship",
        seo_title: "",
        yields: "Servings: 4",
        original_video_url:
          "https://s3.amazonaws.com/video-api-prod/assets/713b1fdd83d84724852505d38b7e31b8/BFV104729_CookingPotatoes100DifferentWays10100MochiSponsored_9x16final.mp4",
        canonical_id: "recipe:8681",
        cook_time_minutes: null,
        promotion: "full",
        video_id: 192057,
      },
    },
    {
      type: "item",
      item: {
        nutrition_visibility: "auto",
        country: "US",
        instructions: [
          {
            start_time: 0,
            appliance: "oven",
            end_time: 0,
            temperature: 400,
            id: 75002,
            position: 1,
            display_text:
              "Preheat the oven to 400˚F (200˚C). LIne a baking sheet with parchment paper.",
          },
          {
            start_time: 4000,
            appliance: null,
            end_time: 9000,
            temperature: null,
            id: 75003,
            position: 2,
            display_text:
              "In a large bowl, toss together the chicken, ½ cup shredded mozzarella, 2 tablespoons Parmesan, some black pepper, the bacon, and ⅓ cup Caesar dressing until evenly combined.",
          },
          {
            start_time: 10649,
            appliance: null,
            end_time: 11983,
            temperature: null,
            id: 75004,
            position: 3,
            display_text:
              "Divide the chicken mixture into 4 piles on the prepared baking sheet, shaping into roughly 2-inch squares.",
          },
          {
            start_time: 12000,
            appliance: null,
            end_time: 14666,
            temperature: null,
            id: 75005,
            position: 4,
            display_text:
              "Place a puff pastry square on top of each pile of chicken, gently pressing the down around the filling to remove any air. Using a fork, press the pastry down all the way around the edges.",
          },
          {
            start_time: 15000,
            appliance: null,
            end_time: 18500,
            temperature: null,
            id: 75006,
            position: 5,
            display_text:
              "Use a pastry brush to generously brush the remaining Caesar dressing over the tops of the puff pastry, then sprinkle with the remaining ¼ cup mozzarella and 1 tablespoon Parmesan and more black pepper.",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 75007,
            position: 6,
            display_text:
              "Bake until the top of the pastry is golden brown and bubbly and the dough has puffed up, about 15 minutes. Let cool on the baking sheet for 5 minutes, then flip over.",
          },
          {
            start_time: 21500,
            appliance: null,
            end_time: 23666,
            temperature: null,
            id: 75008,
            position: 7,
            display_text:
              "Drizzle each chicken bake pastry with more Caesar dressing, then sprinkle with chives, if using, and Parmesan.",
          },
          {
            start_time: 24666,
            appliance: null,
            end_time: 26650,
            temperature: null,
            id: 75009,
            position: 8,
            display_text: "Enjoy!",
          },
        ],
        keywords: "",
        facebook_posts: [],
        language: "eng",
        seo_path: null,
        user_ratings: {
          count_positive: 11,
          score: 0.9166666666666666,
          count_negative: 1,
        },
        price: {
          total: 2650,
          updated_at: "2023-07-06T07:30:08+02:00",
          portion: 650,
          consumption_total: 1300,
          consumption_portion: 300,
        },
        id: 8680,
        brand: null,
        slug: "upside-down-puff-pastry-costco-chicken-bake",
        servings_noun_singular: "serving",
        show_id: 17,
        prep_time_minutes: 10,
        sections: [
          {
            components: [
              {
                raw_text: "1½ cups shredded rotisserie chicken",
                extra_comment: "",
                ingredient: {
                  updated_at: 1526518944,
                  name: "shredded rotisserie chicken",
                  created_at: 1526518944,
                  display_plural: "shredded rotisserie chickens",
                  id: 4104,
                  display_singular: "shredded rotisserie chicken",
                },
                id: 99726,
                position: 1,
                measurements: [
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "190",
                    id: 737260,
                  },
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "1 ½",
                    id: 737257,
                  },
                ],
              },
              {
                raw_text: "¾ cup shredded mozzarella cheese, divided",
                extra_comment: "divided",
                ingredient: {
                  updated_at: 1509035282,
                  name: "shredded mozzarella cheese",
                  created_at: 1493925751,
                  display_plural: "shredded mozzarella cheeses",
                  id: 169,
                  display_singular: "shredded mozzarella cheese",
                },
                id: 99727,
                position: 2,
                measurements: [
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "75",
                    id: 737267,
                  },
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "¾",
                    id: 737264,
                  },
                ],
              },
              {
                raw_text:
                  "3 tablespoons grated Parmesan cheese, divided, plus more for garnish",
                extra_comment: "divided, plus more for garnish",
                ingredient: {
                  updated_at: 1509035159,
                  name: "grated parmesan cheese",
                  created_at: 1497741203,
                  display_plural: "grated parmesan cheeses",
                  id: 1869,
                  display_singular: "grated parmesan cheese",
                },
                id: 99728,
                position: 3,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "3",
                    id: 737263,
                  },
                ],
              },
              {
                raw_text: "Freshly ground black pepper, to taste",
                extra_comment: "to taste",
                ingredient: {
                  updated_at: 1509035282,
                  name: "freshly ground black pepper",
                  created_at: 1493925438,
                  display_plural: "freshly ground black peppers",
                  id: 166,
                  display_singular: "freshly ground black pepper",
                },
                id: 99729,
                position: 4,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "0",
                    id: 737261,
                  },
                ],
              },
              {
                raw_text:
                  "½ cup Caesar dressing, divided, plus more for garnish",
                extra_comment: "divided, plus more for garnish",
                ingredient: {
                  updated_at: 1509035251,
                  name: "caesar dressing",
                  created_at: 1495299554,
                  display_plural: "caesar dressings",
                  id: 555,
                  display_singular: "caesar dressing",
                },
                id: 99730,
                position: 5,
                measurements: [
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "120",
                    id: 737266,
                  },
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "½",
                    id: 737265,
                  },
                ],
              },
              {
                raw_text: "4 strips bacon, cooked and finely chopped",
                extra_comment: "cooked and finely chopped",
                ingredient: {
                  updated_at: 1509035279,
                  name: "bacon",
                  created_at: 1494212643,
                  display_plural: "bacons",
                  id: 214,
                  display_singular: "bacon",
                },
                id: 99731,
                position: 6,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "strip",
                      display_plural: "strips",
                      display_singular: "strip",
                      abbreviation: "strip",
                    },
                    quantity: "4",
                    id: 737258,
                  },
                ],
              },
              {
                raw_text:
                  "1 sheet frozen puff pastry, thawed, cut into 4 squares",
                extra_comment: "thawed, cut into 4 squares",
                ingredient: {
                  updated_at: 1509035112,
                  name: "frozen puff pastry",
                  created_at: 1501595172,
                  display_plural: "frozen puff pastries",
                  id: 2743,
                  display_singular: "frozen puff pastry",
                },
                id: 99732,
                position: 7,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "sheet",
                      display_plural: "sheets",
                      display_singular: "sheet",
                      abbreviation: "sheet",
                    },
                    quantity: "1",
                    id: 737262,
                  },
                ],
              },
              {
                raw_text: "Minced fresh chives, for garnish (optional)",
                extra_comment: "for garnish (optional)",
                ingredient: {
                  updated_at: 1687796878,
                  name: "minced fresh chives",
                  created_at: 1687796878,
                  display_plural: "minced fresh chives",
                  id: 11367,
                  display_singular: "minced fresh chive",
                },
                id: 99733,
                position: 8,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "0",
                    id: 737259,
                  },
                ],
              },
            ],
            name: null,
            position: 1,
          },
        ],
        brand_id: null,
        tags: [],
        nutrition: {
          carbohydrates: 46,
          fiber: 1,
          updated_at: "2023-06-25T08:11:24+02:00",
          protein: 43,
          fat: 85,
          calories: 1130,
          sugar: 1,
        },
        name: "Upside-Down Puff Pastry Costco Chicken Bake",
        compilations: [],
        num_servings: 4,
        buzz_id: null,
        tips_and_ratings_enabled: true,
        aspect_ratio: "9:16",
        show: {
          name: "Tasty",
          id: 17,
        },
        created_at: 1687470849,
        description:
          "Try our take on the viral upside-down puff pastry trend inspired by everyone’s favorite Costco food court item, the chicken bake! These are super easy to make and the combo of chicken, cheese, bacon, and Caesar dressing makes them totally worth the hype!",
        draft_status: "published",
        inspired_by_url: null,
        thumbnail_url:
          "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/452818.jpg",
        thumbnail_alt_text: "",
        total_time_minutes: 25,
        video_url: "https://vid.tasty.co/output/295344/hls24_1687470625.m3u8",
        updated_at: 1687796902,
        credits: [
          {
            name: "Kelly Paige",
            type: "internal",
          },
        ],
        approved_at: 1687796902,
        is_one_top: false,
        servings_noun_plural: "servings",
        renditions: [
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/295344/square_720/1687470625_00001.png",
            file_size: 5346791,
            url: "https://vid.tasty.co/output/295344/square_720/1687470625",
            duration: 28195,
            bit_rate: 1518,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 404,
            minimum_bit_rate: null,
            name: "mp4_404x720",
            maximum_bit_rate: null,
            height: 720,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/295344/square_320/1687470625_00001.png",
            file_size: 2041374,
            url: "https://vid.tasty.co/output/295344/square_320/1687470625",
            duration: 28195,
            bit_rate: 580,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 180,
            minimum_bit_rate: null,
            name: "mp4_180x320",
            maximum_bit_rate: null,
            height: 320,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/295344/landscape_720/1687470625_00001.png",
            file_size: 5346170,
            url: "https://vid.tasty.co/output/295344/landscape_720/1687470625",
            duration: 28195,
            bit_rate: 1517,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 404,
            minimum_bit_rate: null,
            name: "mp4_404x720",
            maximum_bit_rate: null,
            height: 720,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/295344/landscape_480/1687470625_00001.png",
            file_size: 3190896,
            url: "https://vid.tasty.co/output/295344/landscape_480/1687470625",
            duration: 28195,
            bit_rate: 906,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 270,
            minimum_bit_rate: null,
            name: "mp4_270x480",
            maximum_bit_rate: null,
            height: 480,
          },
          {
            container: "ts",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/295344/1445289064805-h2exzu/1687470625_00001.png",
            file_size: null,
            url: "https://vid.tasty.co/output/295344/hls24_1687470625.m3u8",
            duration: 28237,
            bit_rate: null,
            content_type: "application/vnd.apple.mpegurl",
            aspect: "portrait",
            width: 608,
            minimum_bit_rate: 271,
            name: "low",
            maximum_bit_rate: 2379,
            height: 1080,
          },
        ],
        beauty_url: null,
        is_shoppable: true,
        topics: [
          {
            name: "Romantic Dinners",
            slug: "romantic-dinners",
          },
        ],
        total_time_tier: {
          tier: "under_30_minutes",
          display_tier: "Under 30 minutes",
        },
        video_ad_content: "none",
        seo_title: "",
        yields: "Servings: 4",
        original_video_url:
          "https://s3.amazonaws.com/video-api-prod/assets/ab03dbbeb0cc4e678acb1d6926f09da1/BFV106573.mp4",
        canonical_id: "recipe:8680",
        cook_time_minutes: 15,
        promotion: "full",
        video_id: 196281,
      },
    },
    {
      type: "item",
      item: {
        nutrition_visibility: "auto",
        country: "US",
        instructions: [
          {
            start_time: 6000,
            appliance: null,
            end_time: 10166,
            temperature: null,
            id: 74989,
            position: 1,
            display_text:
              "Add the pork ribs to a large bowl and season with the salt, 1½ teaspoons sugar, the garlic powder, and black pepper.",
          },
          {
            start_time: 12633,
            appliance: null,
            end_time: 14133,
            temperature: null,
            id: 74990,
            position: 2,
            display_text:
              "Slice the white parts of the green onions lengthwise and chop the green parts; set the greens aside.",
          },
          {
            start_time: 15966,
            appliance: null,
            end_time: 17100,
            temperature: null,
            id: 74991,
            position: 3,
            display_text:
              "Heat the oil in a large pan over medium heat. Add the shallot, half of the jalapeño, white parts of the green onions, and garlic and sauté until light golden, 3 minutes.",
          },
          {
            start_time: 18000,
            appliance: null,
            end_time: 26833,
            temperature: null,
            id: 74992,
            position: 4,
            display_text:
              "Add the ribs to the aromatics and brown on all sides, about 4 minutes, then add the grated lemongrass, remaining 2½ tablespoons of sugar, the nước màu, fish sauce, enough water to come about halfway up the ribs, the rest of the jalapeño, and the scallion greens. Cover and simmer for 20 minutes, or until the liquid has reduced by half and the ribs are caramelized.",
          },
          {
            start_time: 26834,
            appliance: null,
            end_time: 29300,
            temperature: null,
            id: 74993,
            position: 5,
            display_text:
              "Garnish with sesame seeds and more jalapeño and scallions and serve over rice.",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 3333,
            temperature: null,
            id: 74994,
            position: 6,
            display_text: "Enjoy!",
          },
        ],
        keywords: "",
        facebook_posts: [],
        language: "eng",
        seo_path: null,
        user_ratings: {
          count_positive: 14,
          score: 1,
          count_negative: 0,
        },
        price: {
          total: 2250,
          updated_at: "2023-07-06T07:30:07+02:00",
          portion: 550,
          consumption_total: 1000,
          consumption_portion: 250,
        },
        id: 8678,
        brand: null,
        slug: "asian-sticky-ribs",
        servings_noun_singular: "serving",
        show_id: 17,
        prep_time_minutes: 10,
        sections: [
          {
            components: [
              {
                raw_text: "-2½ pounds pork ribs",
                extra_comment: "",
                ingredient: {
                  updated_at: 1686255469,
                  name: "pork ribs",
                  created_at: 1686255469,
                  display_plural: "pork ribs",
                  id: 11348,
                  display_singular: "pork rib",
                },
                id: 99700,
                position: 1,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "pound",
                      display_plural: "lb",
                      display_singular: "lb",
                      abbreviation: "lb",
                    },
                    quantity: "2 ½",
                    id: 736766,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "kilogram",
                      display_plural: "kg",
                      display_singular: "kg",
                      abbreviation: "kg",
                    },
                    quantity: "2.2",
                    id: 736765,
                  },
                ],
              },
              {
                raw_text: "-1 Tbsp kosher salt",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035289,
                  name: "kosher salt",
                  created_at: 1493307153,
                  display_plural: "kosher salts",
                  id: 11,
                  display_singular: "kosher salt",
                },
                id: 99701,
                position: 2,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "1",
                    id: 736761,
                  },
                ],
              },
              {
                raw_text: "-3 Tbsp sugar, divided",
                extra_comment: "divided",
                ingredient: {
                  updated_at: 1509035288,
                  name: "sugar",
                  created_at: 1493314650,
                  display_plural: "sugars",
                  id: 24,
                  display_singular: "sugar",
                },
                id: 99702,
                position: 3,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "3",
                    id: 736777,
                  },
                ],
              },
              {
                raw_text: "-1 Tbsp garlic powder",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035289,
                  name: "garlic powder",
                  created_at: 1493307128,
                  display_plural: "garlic powders",
                  id: 9,
                  display_singular: "garlic powder",
                },
                id: 99703,
                position: 4,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "1",
                    id: 736764,
                  },
                ],
              },
              {
                raw_text: "-1½ tsp black pepper",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035282,
                  name: "freshly ground black pepper",
                  created_at: 1493925438,
                  display_plural: "freshly ground black peppers",
                  id: 166,
                  display_singular: "freshly ground black pepper",
                },
                id: 99704,
                position: 5,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "teaspoon",
                      display_plural: "teaspoons",
                      display_singular: "teaspoon",
                      abbreviation: "tsp",
                    },
                    quantity: "1 ½",
                    id: 736767,
                  },
                ],
              },
              {
                raw_text:
                  "-3 green onion stalks, whites and green parts separated, plus more for garnish",
                extra_comment:
                  "whites and green parts separated, plus more for garnish",
                ingredient: {
                  updated_at: 1509035173,
                  name: "green onions",
                  created_at: 1496950436,
                  display_plural: "green onions",
                  id: 1669,
                  display_singular: "green onion",
                },
                id: 99705,
                position: 6,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "3",
                    id: 736769,
                  },
                ],
              },
              {
                raw_text: "-1 Tbsp neutral oil",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035091,
                  name: "neutral oil",
                  created_at: 1506802368,
                  display_plural: "neutral oils",
                  id: 3049,
                  display_singular: "neutral oil",
                },
                id: 99706,
                position: 7,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "1",
                    id: 736773,
                  },
                ],
              },
              {
                raw_text: "-1 shallot, minced",
                extra_comment: "minced",
                ingredient: {
                  updated_at: 1509035111,
                  name: "shallot",
                  created_at: 1501605439,
                  display_plural: "shallots",
                  id: 2753,
                  display_singular: "shallot",
                },
                id: 99707,
                position: 8,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "1",
                    id: 736776,
                  },
                ],
              },
              {
                raw_text:
                  "-1 red jalapeño, sliced, divided, plus more for garnish",
                extra_comment: "sliced, divided, plus more for garnish",
                ingredient: {
                  updated_at: 1686254895,
                  name: "red jalapeño",
                  created_at: 1686254895,
                  display_plural: "red jalapeñoes",
                  id: 11346,
                  display_singular: "red jalapeño",
                },
                id: 99708,
                position: 9,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "1",
                    id: 736768,
                  },
                ],
              },
              {
                raw_text: "-6 garlic cloves, minced",
                extra_comment: "minced",
                ingredient: {
                  updated_at: 1509035270,
                  name: "garlic cloves",
                  created_at: 1494874431,
                  display_plural: "garlic cloves",
                  id: 321,
                  display_singular: "garlic clove",
                },
                id: 99709,
                position: 10,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "6",
                    id: 736775,
                  },
                ],
              },
              {
                raw_text: "-2 Tbsp grated lemongrass",
                extra_comment: "",
                ingredient: {
                  updated_at: 1686255494,
                  name: "grated lemongrass",
                  created_at: 1686255494,
                  display_plural: "grated lemongrass",
                  id: 11349,
                  display_singular: "grated lemongras",
                },
                id: 99710,
                position: 11,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "2",
                    id: 736774,
                  },
                ],
              },
              {
                raw_text: "-2 Tbsp nước màu or 1 Tbsp dark soy sauce",
                extra_comment: "or 1 tablespoon dark soy sauce",
                ingredient: {
                  updated_at: 1686255019,
                  name: "nước màu",
                  created_at: 1686255019,
                  display_plural: "nước màus",
                  id: 11347,
                  display_singular: "nước màu",
                },
                id: 99711,
                position: 12,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "2",
                    id: 736763,
                  },
                ],
              },
              {
                raw_text: "-1 ½ Tbsp fish sauce",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035100,
                  name: "fish sauce",
                  created_at: 1504032220,
                  display_plural: "fish sauces",
                  id: 2904,
                  display_singular: "fish sauce",
                },
                id: 99712,
                position: 13,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "1 ½",
                    id: 736771,
                  },
                ],
              },
              {
                raw_text: "-2 cups water, or as needed",
                extra_comment: "or as needed",
                ingredient: {
                  updated_at: 1509035280,
                  name: "water",
                  created_at: 1494124627,
                  display_plural: "waters",
                  id: 197,
                  display_singular: "water",
                },
                id: 99713,
                position: 14,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "2",
                    id: 736772,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "milliliter",
                      display_plural: "mL",
                      display_singular: "mL",
                      abbreviation: "mL",
                    },
                    quantity: "480",
                    id: 736770,
                  },
                ],
              },
              {
                raw_text: "-1 Tbsp sesame seeds, for garnish",
                extra_comment: "for garnish",
                ingredient: {
                  updated_at: 1509035281,
                  name: "sesame seeds",
                  created_at: 1494117789,
                  display_plural: "sesame seeds",
                  id: 182,
                  display_singular: "sesame seed",
                },
                id: 99714,
                position: 15,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "1",
                    id: 736762,
                  },
                ],
              },
            ],
            name: null,
            position: 1,
          },
        ],
        brand_id: null,
        tags: [
          {
            root_tag_type: "meal",
            name: "dinner",
            id: 64486,
            display_name: "Dinner",
            type: "meal",
          },
          {
            root_tag_type: "cuisine",
            name: "asian",
            id: 9295873,
            display_name: "Asian",
            type: "cuisine",
          },
          {
            root_tag_type: "meal",
            name: "pork",
            id: 9299516,
            display_name: "Pork",
            type: "dinner",
          },
        ],
        nutrition: {
          carbohydrates: 20,
          fiber: 39,
          updated_at: "2023-06-10T08:01:05+02:00",
          protein: 36,
          fat: 56,
          calories: 748,
          sugar: 12,
        },
        name: "Asian Sticky Ribs",
        compilations: [],
        num_servings: 4,
        buzz_id: null,
        tips_and_ratings_enabled: true,
        aspect_ratio: "9:16",
        show: {
          name: "Tasty",
          id: 17,
        },
        created_at: 1686241077,
        description:
          "This was one of my mom’s bi-weekly dinners in rotation when I was growing up and it satisfies every flavor profile you could ask for. Sticky and sweet, savory and meaty, AND it’s a super hands-off recipe. Serve with a pot of fresh rice and blanched veggies and enjoy!",
        draft_status: "published",
        inspired_by_url: null,
        thumbnail_url:
          "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/450611.jpg",
        thumbnail_alt_text: "",
        total_time_minutes: 40,
        video_url: "https://vid.tasty.co/output/293244/hls24_1686240796.m3u8",
        updated_at: 1686255608,
        credits: [
          {
            name: "Sarah Banh",
            type: "internal",
          },
        ],
        approved_at: 1686255607,
        is_one_top: false,
        servings_noun_plural: "servings",
        renditions: [
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/293244/square_720/1686240796_00001.png",
            file_size: 7186384,
            url: "https://vid.tasty.co/output/293244/square_720/1686240796",
            duration: 29780,
            bit_rate: 1931,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 404,
            minimum_bit_rate: null,
            name: "mp4_404x720",
            maximum_bit_rate: null,
            height: 720,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/293244/square_320/1686240796_00001.png",
            file_size: 2503250,
            url: "https://vid.tasty.co/output/293244/square_320/1686240796",
            duration: 29780,
            bit_rate: 673,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 180,
            minimum_bit_rate: null,
            name: "mp4_180x320",
            maximum_bit_rate: null,
            height: 320,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/293244/landscape_720/1686240796_00001.png",
            file_size: 7190511,
            url: "https://vid.tasty.co/output/293244/landscape_720/1686240796",
            duration: 29780,
            bit_rate: 1932,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 404,
            minimum_bit_rate: null,
            name: "mp4_404x720",
            maximum_bit_rate: null,
            height: 720,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/293244/landscape_480/1686240796_00001.png",
            file_size: 4124227,
            url: "https://vid.tasty.co/output/293244/landscape_480/1686240796",
            duration: 29780,
            bit_rate: 1108,
            content_type: "video/mp4",
            aspect: "portrait",
            width: 270,
            minimum_bit_rate: null,
            name: "mp4_270x480",
            maximum_bit_rate: null,
            height: 480,
          },
          {
            container: "ts",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/293244/1445289064805-h2exzu/1686240796_00001.png",
            file_size: null,
            url: "https://vid.tasty.co/output/293244/hls24_1686240796.m3u8",
            duration: 29822,
            bit_rate: null,
            content_type: "application/vnd.apple.mpegurl",
            aspect: "portrait",
            width: 608,
            minimum_bit_rate: 273,
            name: "low",
            maximum_bit_rate: 3030,
            height: 1080,
          },
        ],
        beauty_url: null,
        is_shoppable: true,
        topics: [
          {
            name: "Romantic Dinners",
            slug: "romantic-dinners",
          },
          {
            name: "Dinner",
            slug: "dinner",
          },
        ],
        total_time_tier: {
          tier: "under_45_minutes",
          display_tier: "Under 45 minutes",
        },
        video_ad_content: "none",
        seo_title: "",
        yields: "Servings: 4",
        original_video_url:
          "https://s3.amazonaws.com/video-api-prod/assets/af0893d57d394937a5b26367277b9bb2/PorkRibs.mp4",
        canonical_id: "recipe:8678",
        cook_time_minutes: 30,
        promotion: "full",
        video_id: 193567,
      },
    },
    {
      type: "item",
      item: {
        nutrition_visibility: "auto",
        country: "US",
        instructions: [
          {
            start_time: 0,
            appliance: "oven",
            end_time: 0,
            temperature: 350,
            id: 74975,
            position: 1,
            display_text:
              "Preheat the oven to 350ºF (180°C). Grease a 9 x 13-inch baking dish with nonstick spray.",
          },
          {
            start_time: 6000,
            appliance: null,
            end_time: 19000,
            temperature: null,
            id: 74977,
            position: 2,
            display_text:
              "Make the cinnamon topping: In a medium bowl, mix together the butter, brown sugar, salt, flour,  McCormick® Ground Cinnamon, and pecans. Microwave for 30 seconds.",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 74976,
            position: 3,
            display_text:
              "Make the cake: In a large bowl, whisk together the flour, granulated sugar, baking powder, and salt. ",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 74983,
            position: 4,
            display_text:
              "In a medium bowl, whisk together the milk, eggs, and vanilla until well-combined. ",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 74984,
            position: 5,
            display_text:
              "Pour the wet ingredients into the dry ingredients and whisk until mostly incorporated but a few dry streaks remain. Whisk in the melted butter.",
          },
          {
            start_time: 46000,
            appliance: null,
            end_time: 71333,
            temperature: null,
            id: 74978,
            position: 6,
            display_text:
              "Pour half of the batter into the prepared baking dish. Spoon half of the cinnamon topping on top, gently swirling into the batter. Pour the rest of the batter on top, spreading to cover the filling, then spoon the remaining filling on top, swirling into the batter. ",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 74979,
            position: 7,
            display_text:
              "Bake for 25–30 minutes, or until a toothpick inserted into the center of the cake comes out clean (or with just a few crumbs attached). Remove from the oven and let cool.",
          },
          {
            start_time: 75000,
            appliance: null,
            end_time: 95000,
            temperature: null,
            id: 74980,
            position: 8,
            display_text:
              "Make the frosting: In a medium bowl, mix together the cream cheese, powdered sugar, milk, and salt until smooth. If frosting is too thick to be pourable, add a bit more milk until it reaches the desired consistency. ",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 74985,
            position: 9,
            display_text:
              "Drizzle the frosting over the cake, then slice and serve.",
          },
          {
            start_time: 0,
            appliance: null,
            end_time: 0,
            temperature: null,
            id: 74986,
            position: 10,
            display_text: "Enjoy!",
          },
        ],
        keywords: "",
        facebook_posts: [],
        language: "eng",
        seo_path: null,
        user_ratings: {
          count_positive: 24,
          score: 0.96,
          count_negative: 1,
        },
        price: {
          total: 1550,
          updated_at: "2023-07-06T07:30:06+02:00",
          portion: 150,
          consumption_total: 550,
          consumption_portion: 50,
        },
        id: 8677,
        brand: null,
        slug: "cinnamon-roll-coffee-cake",
        servings_noun_singular: "serving",
        show_id: 17,
        prep_time_minutes: null,
        sections: [
          {
            components: [
              {
                raw_text: "n/a",
                extra_comment: "for greasing",
                ingredient: {
                  updated_at: 1520176895,
                  name: "nonstick cooking spray",
                  created_at: 1520176895,
                  display_plural: "nonstick cooking sprays",
                  id: 3826,
                  display_singular: "nonstick cooking spray",
                },
                id: 99688,
                position: 1,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "0",
                    id: 735827,
                  },
                ],
              },
            ],
            name: null,
            position: 1,
          },
          {
            components: [
              {
                raw_text: "½ cup softened butter",
                extra_comment: "softened",
                ingredient: {
                  updated_at: 1509035272,
                  name: "unsalted butter",
                  created_at: 1494806355,
                  display_plural: "unsalted butters",
                  id: 291,
                  display_singular: "unsalted butter",
                },
                id: 99674,
                position: 3,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "stick",
                      display_plural: "sticks",
                      display_singular: "stick",
                      abbreviation: "stick",
                    },
                    quantity: "1",
                    id: 735816,
                  },
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "½",
                    id: 735814,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "115",
                    id: 735812,
                  },
                ],
              },
              {
                raw_text: "½ cup brown sugar",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035289,
                  name: "brown sugar",
                  created_at: 1493307081,
                  display_plural: "brown sugars",
                  id: 6,
                  display_singular: "brown sugar",
                },
                id: 99675,
                position: 4,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "½",
                    id: 735809,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "100",
                    id: 735808,
                  },
                ],
              },
              {
                raw_text: "1 teaspoon salt",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035289,
                  name: "kosher salt",
                  created_at: 1493307153,
                  display_plural: "kosher salts",
                  id: 11,
                  display_singular: "kosher salt",
                },
                id: 99676,
                position: 5,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "teaspoon",
                      display_plural: "teaspoons",
                      display_singular: "teaspoon",
                      abbreviation: "tsp",
                    },
                    quantity: "1",
                    id: 735810,
                  },
                ],
              },
              {
                raw_text: "1 tablespoon flour",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035280,
                  name: "all-purpose flour",
                  created_at: 1494122348,
                  display_plural: "all-purpose flours",
                  id: 185,
                  display_singular: "all-purpose flour",
                },
                id: 99677,
                position: 6,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "1",
                    id: 735815,
                  },
                ],
              },
              {
                raw_text: "3 teaspoons McCormick Cinnamon",
                extra_comment: "",
                ingredient: {
                  updated_at: 1551279374,
                  name: "McCormick® Ground Cinnamon",
                  created_at: 1551279374,
                  display_plural: "McCormick® Ground Cinnamons",
                  id: 5133,
                  display_singular: "McCormick® Ground Cinnamon",
                },
                id: 99678,
                position: 7,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "teaspoon",
                      display_plural: "teaspoons",
                      display_singular: "teaspoon",
                      abbreviation: "tsp",
                    },
                    quantity: "3",
                    id: 735807,
                  },
                ],
              },
              {
                raw_text: "½ cup chopped pecans",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035237,
                  name: "chopped pecans",
                  created_at: 1495678111,
                  display_plural: "chopped pecans",
                  id: 734,
                  display_singular: "chopped pecan",
                },
                id: 99679,
                position: 8,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "½",
                    id: 735836,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "60",
                    id: 735835,
                  },
                ],
              },
            ],
            name: "Cinnamon Topping",
            position: 2,
          },
          {
            components: [
              {
                raw_text: "3 cups flour",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035280,
                  name: "all-purpose flour",
                  created_at: 1494122348,
                  display_plural: "all-purpose flours",
                  id: 185,
                  display_singular: "all-purpose flour",
                },
                id: 99665,
                position: 10,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "3",
                    id: 735822,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "375",
                    id: 735821,
                  },
                ],
              },
              {
                raw_text: "1 cup sugar",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035262,
                  name: "granulated sugar",
                  created_at: 1494989637,
                  display_plural: "granulated sugars",
                  id: 419,
                  display_singular: "granulated sugar",
                },
                id: 99666,
                position: 11,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "1",
                    id: 735825,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "200",
                    id: 735824,
                  },
                ],
              },
              {
                raw_text: "4 teaspoons baking powder",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035288,
                  name: "baking powder",
                  created_at: 1493314647,
                  display_plural: "baking powders",
                  id: 23,
                  display_singular: "baking powder",
                },
                id: 99667,
                position: 12,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "teaspoon",
                      display_plural: "teaspoons",
                      display_singular: "teaspoon",
                      abbreviation: "tsp",
                    },
                    quantity: "4",
                    id: 735832,
                  },
                ],
              },
              {
                raw_text: "1 teaspoon salt",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035289,
                  name: "kosher salt",
                  created_at: 1493307153,
                  display_plural: "kosher salts",
                  id: 11,
                  display_singular: "kosher salt",
                },
                id: 99668,
                position: 13,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "teaspoon",
                      display_plural: "teaspoons",
                      display_singular: "teaspoon",
                      abbreviation: "tsp",
                    },
                    quantity: "1",
                    id: 735811,
                  },
                ],
              },
              {
                raw_text: "1½ cups milk",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035235,
                  name: "whole milk",
                  created_at: 1495732941,
                  display_plural: "whole milks",
                  id: 770,
                  display_singular: "whole milk",
                },
                id: 99669,
                position: 14,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "1 ½",
                    id: 735829,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "milliliter",
                      display_plural: "mL",
                      display_singular: "mL",
                      abbreviation: "mL",
                    },
                    quantity: "360",
                    id: 735828,
                  },
                ],
              },
              {
                raw_text: "2 eggs",
                extra_comment: "",
                ingredient: {
                  updated_at: 1511917107,
                  name: "large eggs",
                  created_at: 1511917107,
                  display_plural: "large eggs",
                  id: 3299,
                  display_singular: "large egg",
                },
                id: 99670,
                position: 15,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "",
                      display_plural: "",
                      display_singular: "",
                      abbreviation: "",
                    },
                    quantity: "2",
                    id: 735826,
                  },
                ],
              },
              {
                raw_text: "2 teaspoons vanilla extract",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035284,
                  name: "vanilla extract",
                  created_at: 1493745620,
                  display_plural: "vanilla extracts",
                  id: 103,
                  display_singular: "vanilla extract",
                },
                id: 99671,
                position: 16,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "teaspoon",
                      display_plural: "teaspoons",
                      display_singular: "teaspoon",
                      abbreviation: "tsp",
                    },
                    quantity: "2",
                    id: 735813,
                  },
                ],
              },
              {
                raw_text: "n/a",
                extra_comment: "melted",
                ingredient: {
                  updated_at: 1509035272,
                  name: "unsalted butter",
                  created_at: 1494806355,
                  display_plural: "unsalted butters",
                  id: 291,
                  display_singular: "unsalted butter",
                },
                id: 99687,
                position: 17,
                measurements: [
                  {
                    unit: {
                      system: "none",
                      name: "stick",
                      display_plural: "sticks",
                      display_singular: "stick",
                      abbreviation: "stick",
                    },
                    quantity: "1",
                    id: 735820,
                  },
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "½",
                    id: 735818,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "115",
                    id: 735817,
                  },
                ],
              },
            ],
            name: "Cake",
            position: 3,
          },
          {
            components: [
              {
                raw_text: "4 ounces cream cheese, softened",
                extra_comment: "softened",
                ingredient: {
                  updated_at: 1509035276,
                  name: "cream cheese",
                  created_at: 1494297000,
                  display_plural: "cream cheeses",
                  id: 242,
                  display_singular: "cream cheese",
                },
                id: 99681,
                position: 19,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "ounce",
                      display_plural: "oz",
                      display_singular: "oz",
                      abbreviation: "oz",
                    },
                    quantity: "4",
                    id: 735831,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "105",
                    id: 735830,
                  },
                ],
              },
              {
                raw_text: "⅓ cup powdered sugar",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035283,
                  name: "powdered sugar",
                  created_at: 1493747135,
                  display_plural: "powdered sugars",
                  id: 144,
                  display_singular: "powdered sugar",
                },
                id: 99682,
                position: 20,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "cup",
                      display_plural: "cups",
                      display_singular: "cup",
                      abbreviation: "c",
                    },
                    quantity: "⅓",
                    id: 735834,
                  },
                  {
                    unit: {
                      system: "metric",
                      name: "gram",
                      display_plural: "g",
                      display_singular: "g",
                      abbreviation: "g",
                    },
                    quantity: "35",
                    id: 735833,
                  },
                ],
              },
              {
                raw_text: "1 tablespoon milk",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035235,
                  name: "whole milk",
                  created_at: 1495732941,
                  display_plural: "whole milks",
                  id: 770,
                  display_singular: "whole milk",
                },
                id: 99683,
                position: 21,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "tablespoon",
                      display_plural: "tablespoons",
                      display_singular: "tablespoon",
                      abbreviation: "tbsp",
                    },
                    quantity: "1",
                    id: 735819,
                  },
                ],
              },
              {
                raw_text: "¼ teaspoon salt",
                extra_comment: "",
                ingredient: {
                  updated_at: 1509035289,
                  name: "kosher salt",
                  created_at: 1493307153,
                  display_plural: "kosher salts",
                  id: 11,
                  display_singular: "kosher salt",
                },
                id: 99684,
                position: 22,
                measurements: [
                  {
                    unit: {
                      system: "imperial",
                      name: "teaspoon",
                      display_plural: "teaspoons",
                      display_singular: "teaspoon",
                      abbreviation: "tsp",
                    },
                    quantity: "¼",
                    id: 735823,
                  },
                ],
              },
            ],
            name: "Cream Cheese Frosting",
            position: 4,
          },
        ],
        brand_id: null,
        tags: [
          {
            root_tag_type: "cooking_style",
            name: "comfort_food",
            id: 64462,
            display_name: "Comfort Food",
            type: "cooking_style",
          },
          {
            root_tag_type: "seasonal",
            name: "christmas",
            id: 64473,
            display_name: "Christmas",
            type: "holidays",
          },
          {
            root_tag_type: "seasonal",
            name: "easter",
            id: 64474,
            display_name: "Easter",
            type: "holidays",
          },
          {
            root_tag_type: "meal",
            name: "breakfast",
            id: 64483,
            display_name: "Breakfast",
            type: "meal",
          },
          {
            root_tag_type: "meal",
            name: "desserts",
            id: 64485,
            display_name: "Desserts",
            type: "meal",
          },
          {
            root_tag_type: "appliance",
            name: "baking",
            id: 64492,
            display_name: "Baking",
            type: "appliance",
          },
          {
            root_tag_type: "appliance",
            name: "bakery_goods",
            id: 65857,
            display_name: "Bakery Goods",
            type: "appliance",
          },
          {
            root_tag_type: "appliance",
            name: "appliance",
            id: 9295811,
            display_name: "Appliance",
            type: "appliance",
          },
        ],
        nutrition: {
          carbohydrates: 51,
          fiber: 11,
          updated_at: "2023-06-07T08:01:07+02:00",
          protein: 6,
          fat: 19,
          calories: 405,
          sugar: 23,
        },
        name: "Cinnamon Roll Coffee Cake",
        compilations: [],
        num_servings: 12,
        buzz_id: null,
        tips_and_ratings_enabled: true,
        aspect_ratio: "1:1",
        show: {
          name: "Tasty",
          id: 17,
        },
        created_at: 1686005528,
        description:
          "Cinnamon rolls mashed up with coffee cake?! Count us in. Don’t forget the cream cheese frosting!",
        draft_status: "published",
        inspired_by_url: null,
        thumbnail_url:
          "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/449848.jpg",
        thumbnail_alt_text: "",
        total_time_minutes: null,
        video_url: "https://vid.tasty.co/output/292747/hls24_1686005519.m3u8",
        updated_at: 1686085487,
        credits: [
          {
            name: "Dylan Keith",
            type: "internal",
          },
        ],
        approved_at: 1686085486,
        is_one_top: false,
        servings_noun_plural: "servings",
        renditions: [
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/292747/square_720/1686005519_00001.png",
            file_size: 25727193,
            url: "https://vid.tasty.co/output/292747/square_720/1686005519",
            duration: 102772,
            bit_rate: 2003,
            content_type: "video/mp4",
            aspect: "square",
            width: 720,
            minimum_bit_rate: null,
            name: "mp4_720x720",
            maximum_bit_rate: null,
            height: 720,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/292747/square_320/1686005519_00001.png",
            file_size: 8727051,
            url: "https://vid.tasty.co/output/292747/square_320/1686005519",
            duration: 102772,
            bit_rate: 680,
            content_type: "video/mp4",
            aspect: "square",
            width: 320,
            minimum_bit_rate: null,
            name: "mp4_320x320",
            maximum_bit_rate: null,
            height: 320,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/292747/landscape_720/1686005519_00001.png",
            file_size: 25732903,
            url: "https://vid.tasty.co/output/292747/landscape_720/1686005519",
            duration: 102772,
            bit_rate: 2004,
            content_type: "video/mp4",
            aspect: "square",
            width: 720,
            minimum_bit_rate: null,
            name: "mp4_720x720",
            maximum_bit_rate: null,
            height: 720,
          },
          {
            container: "mp4",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/292747/landscape_480/1686005519_00001.png",
            file_size: 14852378,
            url: "https://vid.tasty.co/output/292747/landscape_480/1686005519",
            duration: 102772,
            bit_rate: 1157,
            content_type: "video/mp4",
            aspect: "square",
            width: 480,
            minimum_bit_rate: null,
            name: "mp4_480x480",
            maximum_bit_rate: null,
            height: 480,
          },
          {
            container: "ts",
            poster_url:
              "https://img.buzzfeed.com/video-transcoder-prod/output/292747/1445289064805-h2exzu/1686005519_00001.png",
            file_size: null,
            url: "https://vid.tasty.co/output/292747/hls24_1686005519.m3u8",
            duration: 102770,
            bit_rate: null,
            content_type: "application/vnd.apple.mpegurl",
            aspect: "square",
            width: 1080,
            minimum_bit_rate: 271,
            name: "low",
            maximum_bit_rate: 3562,
            height: 1080,
          },
        ],
        beauty_url:
          "https://img.buzzfeed.com/video-api-prod/assets/aadb97224a7143f2813362537ff46c27/CinnamonCake_BeautyPinterest.jpg",
        is_shoppable: true,
        topics: [
          {
            name: "Baked Goods",
            slug: "baked-goods",
          },
          {
            name: "Christmas",
            slug: "christmas",
          },
          {
            name: "Easter",
            slug: "easter",
          },
          {
            name: "Romantic Dinners",
            slug: "romantic-dinners",
          },
          {
            name: "Breakfast",
            slug: "breakfast",
          },
          {
            name: "Desserts",
            slug: "desserts",
          },
        ],
        total_time_tier: null,
        video_ad_content: "editorial_sponsorship",
        seo_title: "",
        yields:
          "Description: Cinnamon rolls mashed up with coffee cake?! Count us in. And don’t forget the cream cheese frosting!",
        original_video_url:
          "https://s3.amazonaws.com/video-api-prod/assets/2b27c2ea28564183926a3e796a6a93bd/BFV103980_MCCORMICK_CinnamonRollCoffeeCake_DF_V2_050223_1X1.mp4",
        canonical_id: "recipe:8677",
        cook_time_minutes: null,
        promotion: "full",
        video_id: 190252,
      },
    },
  ],
};

export default datas;
